### ISSUE TITLE
Fix the slideshow on the locator page.

### ISSUE THREAD

**Issue by Evionis** [CSI-280/primeorcas#33]
The slideshow disappears after a few seconds or after clicking on one of the buttons.

**Comment by NaomiHoniker** [comment]
I was just working on that haha
It's something wrong with line 94's style.display call, but I can't figure out what it is.

**Comment by Evionis** [comment]
Maybe that can be your next project then.

**Comment by NaomiHoniker** [comment]
Fixed! Removed the fade, so it isn't as fancy, but I think it still looks fine.
